language: go
go:
  - "1.9.7"
  - "1.10.3"
  - tip
script:
  - go build
  - go test ./... -v -race -cover -coverprofile=coverage.txt -covermode=atomic
after_script:
  - bash <(curl -s https://codecov.io/bash)
