
name: Publish website to GitHub Pages
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup ssh
      env:
        SSH_PATH: /root/.ssh
      run: |
        # mkdir ~/.ssh
        # echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
        # chmod 600 ~/.ssh/id_rsa

        eval "$(ssh-agent -s)"
        ssh-add - <<< "${{ secrets.DEPLOY_SSH_KEY }}"

        ssh -o StrictHostKeyChecking=no
        # ssh-keyscan -t rsa "github.com" >> "$SSH_PATH/known_hosts"
        # echo "StrictHostKeyChecking no" >> "$SSH_PATH/config"
    - name: Copy Files
      uses: actions/checkout@v2
    - name: Setup Git
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Publish website
      run: cd website/src && yarn install && GIT_USER=$GITHUB_ACTOR CURRENT_BRANCH=master USE_SSH=true yarn run publish-gh-pages
